# Generated by Django 6.0.6 on 2026-10-09 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zip', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('source', models.CharField(choices=[('zip', 'Entered ZIP'), ('device', 'Device location')], default='zip', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_location', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='offers_zipc_lat_63ff51_idx')],
            },
        ),
    ]
