# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsession',
            name='ai_review_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
