# Generated by Django 6.0.6 on 2026-10-10 00:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def backfill_published_at(apps, schema_editor):
    """Reviews written before moderation existed were published at once."""
    Review = apps.get_model("reviews", "Review")
    Review.objects.filter(published_at__isnull=True).update(published_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brandcustomersuspension'),
        ('products', '0003_alter_product_image_url'),
        ('receipts', '0007_backfill_receipt_identities'),
        ('reviews', '0003_replace_review_system'),
        ('wallets', '0002_ledgerentry_is_promotional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='review_campaign_images/%Y/%m/')),
                ('product_context', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('daily_opportunities', models.PositiveIntegerField(default=25)),
                ('product_cooldown_days', models.PositiveIntegerField(default=90)),
                ('one_time_only', models.BooleanField(default=False)),
                ('auto_paused', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('source', models.CharField(choices=[('brand', 'Brand'), ('ai', 'AI suggestion')], default='brand', max_length=10)),
                ('times_used', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Open'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('questions', models.JSONField(blank=True, default=list)),
                ('brand_question', models.CharField(blank=True, max_length=500)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('ai_review_title', models.CharField(blank=True, max_length=255)),
                ('ai_review_content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='uniq_review_per_user_product',
        ),
        migrations.AddField(
            model_name='review',
            name='brand_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='brand_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='flag_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='held_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('held', 'Held for brand response'), ('flagged', 'Flagged by brand (Nibbl reviewing)'), ('removed', 'Removed')], default='published', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='would_recommend',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewcampaign',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_campaigns', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='reviewcampaign',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='review_campaigns', to='products.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='reviews.reviewcampaign'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulvote',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewhelpfulvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewprompt',
            name='review_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='reviews.reviewcampaign'),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallets.hold'),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_sessions', to='products.product'),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sessions', to='receipts.receipt'),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='review_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='reviews.reviewcampaign'),
        ),
        migrations.AddField(
            model_name='reviewsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reviews.reviewsession'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('session__isnull', True)), fields=('user', 'product'), name='uniq_direct_review_per_user_product'),
        ),
        migrations.AddConstraint(
            model_name='reviewhelpfulvote',
            constraint=models.UniqueConstraint(fields=('review', 'user'), name='uniq_helpful_vote'),
        ),
        migrations.AddIndex(
            model_name='reviewsession',
            index=models.Index(fields=['user', 'status'], name='reviews_rev_user_id_a9d01c_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewsession',
            index=models.Index(fields=['review_campaign', 'created_at'], name='reviews_rev_review__54e229_idx'),
        ),
        migrations.RunPython(backfill_published_at, migrations.RunPython.noop),
    ]
