# Generated by Django 6.0.6 on 2026-10-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='consent_brand_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='consent_nibbl_marketing',
            field=models.BooleanField(default=False),
        ),
    ]
