# Generated by Django 6.0.6 on 2026-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_consent_brand_marketing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='allowed_merchants',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cooldown_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deal_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='eligible_product_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fixed_reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='max_rebate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='one_time_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='required_quantity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
