# Generated by Django 6.0.6 on 2026-10-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='is_promotional',
            field=models.BooleanField(default=False),
        ),
    ]
