# Generated by Django 6.0.6 on 2026-07-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('products', '0002_product_flavor_product_format_product_size_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='product',
        ),
        migrations.AddField(
            model_name='campaign',
            name='products',
            field=models.ManyToManyField(related_name='campaigns', to='products.product'),
        ),
    ]
