# Generated by Django 6.0.6 on 2026-09-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_campaign_product_campaign_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='allowed_merchants',
            field=models.TextField(blank=True),
        ),
    ]
