# Generated by Django 6.0.6 on 2026-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_allowed_merchants'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='claim_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deal_type',
            field=models.CharField(choices=[('free', 'Free'), ('bogo_free', 'BOGO Free'), ('bogo_half', 'Buy 1, Get 1 50% Off'), ('buy_x_get_y', 'Buy X, Get $Y Off')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='desired_redemptions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='estimated_redemption_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='fixed_reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_rebate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='offer_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='offer_headline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='campaign',
            name='one_time_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='required_quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='daily_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
