# Generated by Django 6.0.6 on 2026-10-08 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_convert_campaigns_to_deal_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='review_status',
            field=models.CharField(choices=[('not_submitted', 'Not submitted'), ('pending_review', 'Pending review'), ('changes_requested', 'Changes requested'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='not_submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('new', 'New campaign'), ('revision', 'Revision')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campaigns.campaign')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'kind'], name='campaigns_c_status_262953_idx')],
            },
        ),
    ]
