# Generated by Django 6.0.6 on 2026-10-09 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brandcustomersuspension'),
        ('campaigns', '0008_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='retailer_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('added_by_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_retailers', to='brands.brand')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='featured_retailers',
            field=models.ManyToManyField(blank=True, related_name='featured_in', to='campaigns.retailer'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='retailers',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='campaigns.retailer'),
        ),
    ]
