# Generated by Django 6.0.6 on 2026-10-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_seed_retailers'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='geography',
            field=models.CharField(choices=[('nationwide', 'Nationwide'), ('states', 'Selected States'), ('zip_radius', 'ZIP + Radius')], default='nationwide', max_length=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='geography_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaign',
            name='geography_states',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
