# Generated by Django 6.0.6 on 2026-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_geography_campaign_geography_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='meta_pixel_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
