# Generated by Django 6.0.6 on 2026-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brandcustomersuspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandapplication',
            name='checkout_payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='brandapplication',
            name='checkout_promo_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
