# Generated by Django 6.0.6 on 2026-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0004_application_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_pixel_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_pixel_validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
