# Generated by Django 6.0.6 on 2026-10-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_brand_meta_pixel'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
        migrations.AlterField(
            model_name='brandmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Viewer')], default='member', max_length=20),
        ),
    ]
