# Generated by Django 6.0.6 on 2026-10-08 08:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('withdrawal_review_single', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=14)),
                ('withdrawal_review_rolling', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14)),
                ('withdrawal_rolling_days', models.PositiveIntegerField(default=30)),
                ('referrals_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
    ]
