# Generated by Django 6.0.6 on 2026-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='withdrawal_sms_required',
            field=models.BooleanField(default=False),
        ),
    ]
