# Generated by Django 6.0.6 on 2026-10-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_platformsettings_withdrawal_sms_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformsettings',
            name='withdrawal_sms_required',
        ),
    ]
