# Generated by Django 6.0.6 on 2026-10-09 06:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_platformsettings_withdrawal_sms_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='brand_interest_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.15'), max_digits=4),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='going_fast_percent',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='ranking_prior_redemptions',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='ranking_prior_views',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='store_match_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.25'), max_digits=4),
        ),
    ]
