# Generated by Django 6.0.6 on 2026-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_platformsettings_brand_interest_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='device_checks_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='max_accounts_per_device',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='max_accounts_per_ip_daily',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='referral_flag_fraud_signals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='referral_flag_shared_device',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='referral_flag_shared_network',
            field=models.BooleanField(default=True),
        ),
    ]
