# Generated by Django 6.0.6 on 2026-10-07 03:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_stripecustomer'),
        ('brands', '0002_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRefill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=False)),
                ('threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255)),
                ('last_refilled_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_refill', to='brands.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
