# Generated by Django 6.0.6 on 2026-10-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_autorefill'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_active_campaigns',
            field=models.PositiveIntegerField(default=1, help_text='How many campaigns a brand on this plan may run at once.'),
        ),
    ]
