# Generated by Django 6.0.6 on 2026-10-08 02:44

from django.db import migrations

# Master spec: Starter 1 / Pro 3 / Scale 10 active campaigns.
LIMITS = {"starter": 1, "pro": 3, "scale": 10}


def set_limits(apps, schema_editor):
    Plan = apps.get_model("billing", "Plan")
    for slug, limit in LIMITS.items():
        Plan.objects.filter(slug=slug).update(max_active_campaigns=limit)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_plan_max_active_campaigns'),
    ]

    operations = [
        migrations.RunPython(set_limits, noop),
    ]
