# Generated by Django 6.0.6 on 2026-10-10 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_promocode_promocoderedemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_keep_campaign_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='subscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan'),
        ),
    ]
