# Generated by Django 6.0.6 on 2026-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutmethod',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payoutmethod',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
