# Generated by Django 6.0.6 on 2026-10-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0003_approve_existing_payout_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
