# Generated by Django 6.0.6 on 2026-10-08 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_approved'),
        ('brands', '0003_brandcustomersuspension'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opted_in', models.BooleanField(default=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_consents', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('brand__isnull', True)), fields=('user',), name='uniq_nibbl_marketing_consent'), models.UniqueConstraint(condition=models.Q(('brand__isnull', False)), fields=('user', 'brand'), name='uniq_brand_marketing_consent')],
            },
        ),
    ]
