# Generated by Django 6.0.6 on 2026-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_marketingconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_verified_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawals_paused_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
