# Generated by Django 6.0.6 on 2026-10-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_last_verified_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingconsent',
            name='source',
            field=models.CharField(choices=[('claim', 'Offer claim checkbox')], default='claim', max_length=20),
        ),
    ]
