# Generated by Django 6.0.6 on 2026-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_marketing_consent_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='brand_application',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='verification_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
