# Generated by Django 6.0.6 on 2026-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_seed_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('receipt_reminder', 'Upload your receipt'), ('review_reminder', 'Finish your review'), ('rewards_waiting', 'You have rewards waiting'), ('new_offers', 'New offers available'), ('inactive', 'We miss you'), ('promotional', 'Promotional'), ('auto_refill_failed', 'Automatic refill failed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('receipt_reminder', 'Upload your receipt'), ('review_reminder', 'Finish your review'), ('rewards_waiting', 'You have rewards waiting'), ('new_offers', 'New offers available'), ('inactive', 'We miss you'), ('promotional', 'Promotional'), ('auto_refill_failed', 'Automatic refill failed')], max_length=30, unique=True),
        ),
    ]
