# Generated by Django 6.0.6 on 2026-10-10 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_brand_timezone_viewer_role'),
        ('notifications', '0004_alter_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('receipt_reminder', 'Upload your receipt'), ('review_reminder', 'Finish your review'), ('rewards_waiting', 'You have rewards waiting'), ('new_offers', 'New offers available'), ('inactive', 'We miss you'), ('promotional', 'Promotional'), ('auto_refill_failed', 'Automatic refill failed'), ('campaign_review', 'Campaign review update'), ('receipt_review_needed', 'Receipt waiting for your review'), ('low_rating_review', 'Low-rating review to respond to')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('receipt_reminder', 'Upload your receipt'), ('review_reminder', 'Finish your review'), ('rewards_waiting', 'You have rewards waiting'), ('new_offers', 'New offers available'), ('inactive', 'We miss you'), ('promotional', 'Promotional'), ('auto_refill_failed', 'Automatic refill failed'), ('campaign_review', 'Campaign review update'), ('receipt_review_needed', 'Receipt waiting for your review'), ('low_rating_review', 'Low-rating review to respond to')], max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='BrandNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('receipt_reminder', 'Upload your receipt'), ('review_reminder', 'Finish your review'), ('rewards_waiting', 'You have rewards waiting'), ('new_offers', 'New offers available'), ('inactive', 'We miss you'), ('promotional', 'Promotional'), ('auto_refill_failed', 'Automatic refill failed'), ('campaign_review', 'Campaign review update'), ('receipt_review_needed', 'Receipt waiting for your review'), ('low_rating_review', 'Low-rating review to respond to')], max_length=30)),
                ('email', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'brand', 'notification_type'), name='uniq_brand_notif_pref')],
            },
        ),
    ]
