# Generated by Django 6.0.6 on 2026-08-29 11:40

from django.db import migrations, models


def clear_legacy_fingerprints(apps, schema_editor):
    """Retire fingerprints produced by the previous algorithm.

    The old fingerprint mixed in the uploaded image's bytes, so two photos of
    one physical receipt hashed differently — it could not detect the duplicate
    it exists to catch. Those values are not comparable with the new 5-field
    hashes, and any blank ones would collide under the new UNIQUE index (only
    NULL is exempt), so they are cleared to NULL.
    """
    Receipt = apps.get_model("receipts", "Receipt")
    Receipt.objects.all().update(fingerprint=None)


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RunPython(
            clear_legacy_fingerprints, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='receipt',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
