# Generated by Django 6.0.6 on 2026-09-06 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('campaigns', '0003_campaign_allowed_merchants'),
        ('products', '0003_alter_product_image_url'),
        ('receipts', '0003_receipt_full_fingerprint'),
        ('reservations', '0002_alter_reservation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='full_fingerprint',
        ),
        migrations.AddField(
            model_name='receipt',
            name='merchant_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='product_description_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='purchase_date_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='purchase_time_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='receiptlineitem',
            name='description_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('merchant_hash', 'purchase_date_hash', 'purchase_time_hash', 'product_description_hash'), name='uniq_receipt_identity_per_product'),
        ),
    ]
