# Generated by Django 6.0.6 on 2026-10-09 05:07

import django.db.models.deletion
from django.conf import settings
import datetime as dt

from django.conf import settings
from django.db import migrations, models


def backfill_deadlines(apps, schema_editor):
    """Existing review items: deadline = receipt submission + the window."""
    Item = apps.get_model("receipts", "ManualReviewItem")
    window = dt.timedelta(days=settings.MANUAL_REVIEW_AUTO_APPROVE_DAYS)
    for item in Item.objects.filter(deadline_at__isnull=True).select_related("receipt"):
        item.deadline_at = item.receipt.created_at + window
        item.save(update_fields=["deadline_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_brandcustomersuspension'),
        ('products', '0003_alter_product_image_url'),
        ('receipts', '0004_receipt_identity_hashes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreviewitem',
            name='calculated_reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='manualreviewitem',
            name='confirmed_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.product'),
        ),
        migrations.AddField(
            model_name='manualreviewitem',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manualreviewitem',
            name='outcome',
            field=models.CharField(blank=True, choices=[('brand_approved', 'Brand approved'), ('auto_approved', 'Automatically Approved — Review Deadline Passed'), ('alias_approved', 'Approved after product alias'), ('brand_rejected', 'Brand rejected'), ('auto_rejected', 'Automatically rejected')], max_length=20),
        ),
        migrations.AddField(
            model_name='manualreviewitem',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('outside_period', 'Purchase outside reservation period'), ('retailer_not_eligible', 'Required retailer not eligible'), ('item_not_found', 'Eligible item not found'), ('quantity_not_met', 'Required quantity not met'), ('price_not_visible', 'Price not visible'), ('unreadable', 'Receipt unreadable after resubmission'), ('duplicate', 'Duplicate receipt or previously allocated item'), ('final_resubmission', 'Final resubmission rejected')], max_length=30),
        ),
        migrations.AddField(
            model_name='manualreviewitem',
            name='selected_lines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='manualreviewitem',
            index=models.Index(fields=['status', 'deadline_at'], name='receipts_ma_status_bf62c6_idx'),
        ),
        migrations.RunPython(backfill_deadlines, migrations.RunPython.noop),
    ]
