# Generated by Django 6.0.6 on 2026-10-09 06:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_manual_review_decisions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('core_hash', models.CharField(db_index=True, max_length=64)),
                ('transaction_number', models.CharField(blank=True, max_length=100)),
                ('register_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptUnitAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_hash', models.CharField(max_length=64)),
                ('unit_index', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='receipt',
            name='uniq_receipt_identity_per_product',
        ),
        migrations.AddField(
            model_name='receipt',
            name='register_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='receiptidentity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_identities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='receipts.receiptidentity'),
        ),
        migrations.AddField(
            model_name='receiptunitallocation',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receipts.receiptidentity'),
        ),
        migrations.AddField(
            model_name='receiptunitallocation',
            name='line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='receipts.receiptlineitem'),
        ),
        migrations.AddField(
            model_name='receiptunitallocation',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='receipts.receipt'),
        ),
        migrations.AddConstraint(
            model_name='receiptidentity',
            constraint=models.UniqueConstraint(fields=('core_hash', 'transaction_number', 'register_number'), name='uniq_receipt_identity'),
        ),
        migrations.AddConstraint(
            model_name='receiptunitallocation',
            constraint=models.UniqueConstraint(fields=('identity', 'line_hash', 'unit_index'), name='uniq_receipt_unit'),
        ),
    ]
