# Generated by Django 6.0.6 on 2026-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_backfill_receipt_identities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudflag',
            name='reason',
            field=models.CharField(choices=[('duplicate', 'Duplicate receipt'), ('no_match', 'Product not matched'), ('velocity', 'Too many active claims'), ('manual', 'Manually flagged'), ('device', 'Shared device or network')], max_length=20),
        ),
    ]
